import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
    <Sidebar />
    <div className={styles.container}>
     
      <Head>
        <title>Create Next App</title>
     
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Lets build Watsapp 2.0</h1>
     
    </div>
    </div>
  )
}
